### ISSUE TITLE
Makefile rule error

### ISSUE THREAD

**Issue by Lawrence-Godfrey** [UCT-EE-OCW/EEE4120F#1]
The following rule should be `Prac3:` not `Prac4:`

https://github.com/UCT-EE-OCW/EEE4120F-Pracs/blob/96ae8d5066519a479b1935805b71e2c3f67d9cc8/Prac3/makefile#L25

**Comment by kcranky** [comment]
Thanks for pointing this out. Resolved in https://github.com/UCT-EE-OCW/EEE4120F-Pracs/commit/02114c8e468fd5b14021fa27e0c486a815fef902
